# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YLPopDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YLPopDemo
  pod 'SnapKit'

  target 'YLPopDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YLPopDemoUITests' do
    # Pods for testing
  end

end
